version: "3.7"

services:  
  backend:
    build: ./backend
    # image: gitlab.praktikum-services.ru:5050/std-016-032/momo-store/momo-backend:latest
    networks:
      sausage-store:
    restart: unless-stopped

  frontend:
    # image: gitlab.praktikum-services.ru:5050/std-016-032/momo-store/momo-frontend:latest
    build: 
      context: ./frontend
      args:
        VUE_APP_API_URL: /api
    ports:
      - "80:80"
    networks:
      - sausage-store
    volumes:
      - ./frontend/.nginx-conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

networks:
  sausage-store:

